### ISSUE TITLE
I want to download this RE_RSZ

### ISSUE THREAD

**Issue by azmeer830216** [alphazolam/RE_RSZ#15]
Hello....
Im a little loss here...
I can't seem to find how to download this file with this instruction : 
Download via "Code -> Download as ZIP"
Please show/enlighten me...
Thanks in advanced!

**Comment by SkebbZ** [comment]
> Hello.... Im a little loss here... I can't seem to find how to download this file with this instruction : Download via "Code -> Download as ZIP" Please show/enlighten me... Thanks in advanced!

![Skjermbilde 2023-08-27 123836](https://github.com/alphazolam/RE_RSZ/assets/12503022/3f6c3ae4-13ba-42ad-ba17-17643aaac5d5)

**Comment by azmeer830216** [comment]
Thanks for the response...
It seems that i can't find the functions like u show there...like that function is not there in my view...
Im trying to download the file using my android phone..is that function that u show is coming from using the pc?
Is this site was not android user friendly??
Please enlighten me more....
Thanks in advanced!

[This was shown on my side, i have already try to go all the button/tab but failed to find the download function.]

![IMG_20230827_204502](https://github.com/alphazolam/RE_RSZ/assets/93719467/1a68812d-2825-43fc-8ad2-e214421e4a22)

EDIT : anyway....i have already download all the files one by one...just wanna know where the download function that can be download all the file in zip file like u show there...

**Comment by dtlnor** [comment]
There is no reason to download a repository on a mobile device, especially on a phone. It's not about friendly.
If you don't know how to use GitHub, try to Google search about it. There are bunch of videos and articles that teach you "how to".

**Comment by SkebbZ** [comment]
Try using desktop view in your browser (three dots near URL, then toggle it there).

That being said, dtlnor is correct. Can't see why you would want to download it on a phone.

**Comment by azmeer830216** [comment]
Thanks for the response...much appreciated!
Thread closed.
