### ISSUE TITLE
An error ocurred in the file. Would you like to debug this file?

### ISSUE THREAD

**Issue by WilliamKL2** [alphazolam/RE_RSZ#3]
An error ocurred in the file. Would you like to debug this file?
this is the message I get from the 010 editor when I try to run the template on a file, a file that I already have previously edited.

the file is Lance.rcol.18, found in natives\STM\player\hit\Lance.rcol.18

**the output from 010 editor:**
Executing template 'E:\OneDrive\Área de Trabalho\RE_RSZ-main\RE_RSZ.bt' on 'E:\OneDrive\Área de Trabalho\Nova pasta\re_chunk_000.pak.patch_00y\natives\STM\player\hit\Lance.rcol.18'...

Parsing JSON e:\onedrive\Área de trabalho\re_rsz-main\rszmhrise.json
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [1]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [2]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [3]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [4]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [5]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [6]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [7]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [8]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [9]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [10]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [11]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [12]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [13]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [14]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [15]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [16]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [17]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [18]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [19]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [20]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [21]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [22]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [23]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [24]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [25]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [26]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [27]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [28]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [29]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [30]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [31]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [32]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [33]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [34]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [35]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [36]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [37]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [38]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [39]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [40]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [41]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [42]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [43]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [44]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [45]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [46]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [47]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [48]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [49]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [50]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [51]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [52]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [53]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [54]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [55]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [56]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [57]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [58]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [59]
Class 3531645801 Not Initialized! not detected in JSON!

ERROR: Missing struct for D280A369 Not Initialized! [60]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [61]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [62]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [63]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [64]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [65]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [66]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [67]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [68]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [69]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [70]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [71]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [72]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [73]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [74]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [75]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [76]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [77]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [78]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [79]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [80]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [81]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [82]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [83]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [84]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [85]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [86]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [87]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [88]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [89]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [90]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [91]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [92]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [93]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [94]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [95]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [96]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [97]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [98]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [99]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [100]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [101]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [102]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [103]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [104]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [105]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [106]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [107]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [108]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [109]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [110]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [111]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [112]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [113]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [114]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [115]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [116]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [117]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [118]
Class 4150774079 Not Initialized! not detected in JSON!

ERROR: Missing struct for F767C93F Not Initialized! [119]
Class 2998556266 Not Initialized! not detected in JSON!

ERROR: Missing struct for B2BA566A Not Initialized! [120]
*WARNING Line 5032: Empty structure. 
*WARNING Line 5029: Empty structure. 
*ERROR Line 2242: Array index out of bounds.

**Comment by praydog** [comment]
If you're on the Sunbreak demo, you might want to try @dtlnor's fork that uses my dump for the demo: https://github.com/dtlnor/RE_RSZ

I will update the rszmhrise.json here once Sunbreak actually releases.

**Comment by WilliamKL2** [comment]
It's not the Sunbreak demo, this file is from Rise base game.

**Comment by praydog** [comment]
Probably try reinstalling the template. Re-download everything. The missing structures should be in the JSON file.

**Comment by alphazolam** [comment]
This file worked for me when I just tested it. It sounds like a version error, where the template is trying to use the JSON dump from the wrong game (although that shouldn't be, since MHRise is the default version). Try turning off "AutoDetectGame" option at the top of the RE_RSZ.bt file. These files are generally all very similar between games and it can be difficult to auto-detect which JSON dump to use
