### ISSUE TITLE
PBF template needed to be update for Sunbreak

### ISSUE THREAD

**Issue by gradashy** [alphazolam/RE_RSZ#4]
If you try to use it in the PBF files of Sunbreak, it will cause infinite loadings while trying to load the character that is using it.

**Comment by alphazolam** [comment]
I assume you mean that the game is infinite loading after applying an edit to a new Sunbreak PFB file? The template seems to be reading Sunbreak PFBs fine. Are you adding a new via.Folder? The game will infinite load if any of the CRCs in InstanceInfos are from the old version of the game

**Comment by gradashy** [comment]
Yes, I was adding a new one to add support the chain file to the armor piece (leg and chest), and its results in the infinite loading as you mention. The Template reads and edits, but cause this problem

**Comment by alphazolam** [comment]
Ok I am not sure if this was the problem, but I updated the FolderInfo Writer to have the updated CombinedKey (hash + CRC) for Sunbreak, so it should stop infinite loading when adding via.Folders in that game. Adding other resources would only cause infinite loading if they could not be found.

**Comment by gradashy** [comment]
It worked like butter! Thanks, Alpha!
