### ISSUE TITLE
Field "struct Groups" not loading on Rcol file

### ISSUE THREAD

**Issue by Maxlipeman** [alphazolam/RE_RSZ#5]
I tried opening the file "GreatSword.rcol.20" and it gives this error: "ERROR Line 5916: Template passed end of file at variable 'CombinedKeys". The fields where you can modify the motion values of attacks seems to load fine, but the "struct Groups" mentioned on the title doesn't want to load. Sorry if this is hard to understand, english is not my first language.

**Comment by alphazolam** [comment]
Alright I fixed it. There are two new unknown ints in the rcol.20 file header.

**Comment by Maxlipeman** [comment]
OMG Thank you! Now time for me to go back to modding.
