### ISSUE TITLE
WriteRSZVariable will not write proper unsigned values

### ISSUE THREAD

**Issue by Silvris** [alphazolam/RE_RSZ#8]
As stated in title. The problem comes from Atoi's return type, since it only supports signed int, and not unsigned.

**Comment by alphazolam** [comment]
Thanks, I fixed this for UInts and also made Data types try to detect whether you want unsigned or signed based on what you type in WriteRSZVariable. If there's still any issues with it (I know there are still some with UInt64s above the int64 max), you can put the correct value into "uint data" or "uint64 data", found inside the RSZVariable
